name: 'ECS force new deployment'
description: 'Forcing new deployments for all services matching tag filters'
branding:
  icon: 'activity'
  color: 'white'
inputs:
  cluster:
    description: "ECS cluster name"
    required: true
  tag_filters:
    description: "Tag filters for resource API"
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
